name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          
      - name: Build Docker image
        run: docker build -t jesseqin/my-fastapi-app:latest .

      - name: Push Docker image to DockerHub
        run: docker push jesseqin/my-fastapi-app:latest